/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:74bec477-7aec-48bc-a12f-004e566e34d5",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_TUtsQ30gB",
    "aws_user_pools_web_client_id": "1aenjlmae668j64lm8venn4dh9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yj4mvn52xndxtpbqo4p7rjhjoa.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "cafeutil-20200613074608-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://d14fr1tnxookkz.cloudfront.net"
};


export default awsmobile;
